version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: test
    environment:
      - MONGO_URI=mongodb://mongo:27017/test
    
  mongo:
    image: mongo:4.4.21
    container_name: mongo
    logging:
      driver: none
    ports:
      - 27017:27017
  