apiVersion: v1
kind: Service
metadata:
  name: nestjs-k8s
spec:
  selector:
    app: nestjs-k8s
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 8080
      nodePort: 30000
  type: LoadBalancer