name: Ci/CD Pipeline

env:
  DOCKER_COMPOSE_FILE: 'docker-compose-test.yml'
  APP_NAME: 'nestjs-k8s'
  CLUSTER_NAME: 'demo-cluster'
  REGION: 'eu-central-1'
  TAG: ${{ github.sha }}

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  cicd-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Test Docker images
        run: |
          docker compose -f $DOCKER_COMPOSE_FILE pull
          docker compose -f $DOCKER_COMPOSE_FILE build

      - name: Run tests
        run: docker compose -f $DOCKER_COMPOSE_FILE up --abort-on-container-exit --exit-code-from test --attach test
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}:${{ env.TAG }}
      
      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
      
      - name: Deploy to EKS
        run: |
          kubectl rollout restart -f k8s || kubectl apply -f k8s