name: Ci/CD Pipeline

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  cicd-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build test image
        run: docker build -t test-image -f Dockerfile.test .
      
      - name: Run tests
        run: docker run test-image
      
      - name: Build production image
        run: docker build -t medazizkhayati/nestjs-k8s .