name: Ci/CD Pipeline

env:
  DOCKER_COMPOSE_FILE: 'docker-compose-test.yml'

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  cicd-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Test Docker images
        run: |
          docker compose -f $DOCKER_COMPOSE_FILE pull
          docker compose -f $DOCKER_COMPOSE_FILE build

      - name: Run tests
        run: docker compose -f $DOCKER_COMPOSE_FILE up --abort-on-container-exit --exit-code-from test --attach test

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: medazizkhayati/nestjs-k8s:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
